# Generated by Django 3.2 on 2021-04-11 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BesoinProdModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('categorie', models.CharField(max_length=200)),
                ('prix', models.FloatField()),
                ('marque', models.CharField(max_length=200, null=True)),
                ('couleur', models.CharField(max_length=200, null=True)),
                ('variete', models.CharField(max_length=200, null=True)),
                ('quantite', models.FloatField()),
                ('descr', models.TextField()),
            ],
            options={
                'db_table': 'besoinprod',
            },
        ),
        migrations.CreateModel(
            name='EtatProdModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_produit', models.IntegerField()),
                ('nom', models.CharField(max_length=200)),
                ('categorie', models.CharField(max_length=200)),
                ('prix', models.FloatField()),
                ('marque', models.CharField(max_length=200, null=True)),
                ('couleur', models.CharField(max_length=200, null=True)),
                ('variete', models.CharField(max_length=200, null=True)),
                ('quantite', models.FloatField()),
                ('descr', models.TextField()),
            ],
            options={
                'db_table': 'etatprod',
            },
        ),
        migrations.CreateModel(
            name='ProduitModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('categorie', models.CharField(max_length=200)),
                ('prix', models.FloatField()),
                ('marque', models.CharField(max_length=200, null=True)),
                ('couleur', models.CharField(max_length=200, null=True)),
                ('variete', models.CharField(max_length=200, null=True)),
                ('quantite', models.FloatField()),
                ('descr', models.TextField()),
                ('img_prod', models.FileField(upload_to='')),
            ],
            options={
                'db_table': 'produit',
            },
        ),
    ]
