# Generated by Django 3.2 on 2021-04-11 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CandidatModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('poste', models.CharField(max_length=200)),
                ('specialite', models.CharField(max_length=200, null=True)),
                ('niveau', models.CharField(max_length=200)),
                ('experience', models.CharField(max_length=200, null=True)),
                ('pays', models.CharField(max_length=200)),
                ('ville', models.CharField(max_length=200)),
                ('motivation', models.CharField(max_length=200, null=True)),
                ('cv_candidat', models.FileField(upload_to='')),
                ('piece_jointe_cand', models.FileField(upload_to='')),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'candidat',
            },
        ),
        migrations.CreateModel(
            name='DemissionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_personnel', models.IntegerField()),
                ('motif', models.CharField(max_length=200)),
                ('lettre', models.FileField(upload_to='')),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'demission',
            },
        ),
        migrations.CreateModel(
            name='LicenciementModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_personnel', models.IntegerField()),
                ('motif', models.CharField(max_length=200)),
                ('piece_licenciement', models.FileField(upload_to='')),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'licenciement',
            },
        ),
        migrations.CreateModel(
            name='OffreModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poste', models.CharField(max_length=200)),
                ('specialite', models.CharField(max_length=200)),
                ('niveau', models.CharField(max_length=200)),
                ('experience', models.CharField(max_length=200)),
                ('pays', models.CharField(max_length=200)),
                ('ville', models.CharField(max_length=200)),
                ('type_contrat', models.CharField(max_length=200)),
                ('details', models.CharField(max_length=200, null=True)),
                ('date_pubplication', models.DateField()),
                ('date_limite', models.DateField()),
                ('piece_offre', models.FileField(upload_to='')),
            ],
            options={
                'db_table': 'offre',
            },
        ),
    ]
