# Generated by Django 3.2 on 2021-04-11 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('categorie', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('acces', models.CharField(max_length=200, null=True)),
                ('doc', models.FileField(upload_to='')),
                ('date_ajout', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'document',
            },
        ),
    ]
