# Generated by Django 3.2 on 2021-04-11 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonnelModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('date_naissance', models.DateField()),
                ('lieu_naissance', models.CharField(max_length=200)),
                ('telephone', models.FloatField()),
                ('password', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('email_pro', models.EmailField(max_length=254)),
                ('pays', models.CharField(max_length=200)),
                ('ville', models.CharField(max_length=200)),
                ('quartier', models.CharField(max_length=200)),
                ('date_recrutement', models.DateField()),
                ('service', models.CharField(max_length=200)),
                ('poste', models.CharField(max_length=200)),
                ('acces', models.CharField(max_length=200)),
                ('diplome_recrutement', models.CharField(max_length=200)),
                ('type_contrat', models.CharField(max_length=200)),
                ('cv', models.FileField(upload_to='')),
                ('photo', models.FileField(upload_to='')),
                ('num_cni', models.CharField(max_length=200)),
                ('contrat', models.FileField(upload_to='')),
                ('salaire', models.IntegerField()),
            ],
            options={
                'db_table': 'personnel',
            },
        ),
    ]
