# Generated by Django 3.2 on 2021-04-11 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AchatModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_projet', models.IntegerField()),
                ('designation', models.CharField(max_length=200)),
                ('objet', models.CharField(max_length=200)),
                ('prix', models.IntegerField()),
                ('quantite', models.IntegerField()),
                ('piece_facture', models.FileField(upload_to='')),
                ('date', models.DateTimeField()),
            ],
            options={
                'db_table': 'achat',
            },
        ),
        migrations.CreateModel(
            name='CapitalModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origine', models.CharField(max_length=200)),
                ('objet', models.CharField(max_length=200)),
                ('details', models.CharField(max_length=200, null=True)),
                ('montant', models.FloatField()),
                ('piece_capital', models.FileField(upload_to='')),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'capital',
            },
        ),
        migrations.CreateModel(
            name='CreditModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origine', models.CharField(max_length=200)),
                ('objet', models.CharField(max_length=200)),
                ('details', models.TextField(null=True)),
                ('montant', models.FloatField()),
                ('piece_credit', models.FileField(upload_to='')),
                ('date_remboursement', models.DateTimeField()),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'credit',
            },
        ),
        migrations.CreateModel(
            name='PaiementEntrantModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_projet', models.IntegerField()),
                ('nature', models.CharField(max_length=200)),
                ('details', models.TextField()),
                ('montant', models.FloatField()),
                ('montant_restant', models.FloatField()),
                ('piece_entree', models.FileField(upload_to='')),
                ('date', models.DateTimeField()),
            ],
            options={
                'db_table': 'paiemententrant',
            },
        ),
        migrations.CreateModel(
            name='PaiementManoeuvreModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_projet', models.IntegerField()),
                ('travail', models.CharField(max_length=200)),
                ('nom', models.CharField(max_length=200)),
                ('no_cni', models.CharField(max_length=200, null=True)),
                ('duree', models.IntegerField()),
                ('salaire', models.FloatField()),
                ('date', models.DateTimeField()),
            ],
            options={
                'db_table': 'paiementmanoeuvre',
            },
        ),
        migrations.CreateModel(
            name='PaiementSortantModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_projet', models.IntegerField()),
                ('sujet', models.CharField(max_length=200)),
                ('objet', models.CharField(max_length=200)),
                ('details', models.TextField(null=True)),
                ('montant', models.FloatField()),
                ('piece_recu', models.FileField(upload_to='')),
                ('date', models.DateTimeField()),
            ],
            options={
                'db_table': 'paiementsortant',
            },
        ),
        migrations.CreateModel(
            name='RemboursementModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_credit', models.IntegerField()),
                ('nature', models.CharField(max_length=200, null=True)),
                ('details', models.TextField()),
                ('montant', models.FloatField()),
                ('piece_remboursement', models.FileField(upload_to='')),
                ('montant_restant', models.FloatField()),
                ('date', models.DateTimeField()),
            ],
            options={
                'db_table': 'remboursement',
            },
        ),
    ]
