# Generated by Django 3.2 on 2021-04-11 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaterielModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('categorie', models.CharField(max_length=200)),
                ('quantite', models.FloatField()),
                ('prix', models.FloatField()),
                ('marque', models.CharField(max_length=200, null=True)),
                ('couleur', models.CharField(max_length=200, null=True)),
                ('variete', models.CharField(max_length=200, null=True)),
                ('guide', models.FileField(upload_to='')),
                ('descr', models.CharField(max_length=200)),
                ('date_ajout', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'materiel',
            },
        ),
    ]
