# Generated by Django 3.2 on 2021-04-11 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnnonceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objet', models.CharField(max_length=200)),
                ('texte', models.CharField(max_length=5000)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('piece_annonce', models.FileField(upload_to='')),
            ],
            options={
                'db_table': 'annonce',
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_conference', models.IntegerField()),
                ('id_personnel', models.IntegerField()),
                ('id_cible', models.IntegerField()),
                ('texte', models.CharField(max_length=5000)),
                ('piece_chat', models.FileField(upload_to='')),
                ('heure', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'chat',
            },
        ),
        migrations.CreateModel(
            name='ConferenceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objet', models.CharField(max_length=200)),
                ('frequence', models.CharField(max_length=200)),
                ('date', models.DateField(null=True)),
                ('heure', models.TimeField()),
            ],
            options={
                'db_table': 'conference',
            },
        ),
        migrations.CreateModel(
            name='InvitationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_conference', models.IntegerField()),
                ('id_personnel', models.IntegerField()),
            ],
            options={
                'db_table': 'invitation',
            },
        ),
        migrations.CreateModel(
            name='NoteModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_note', models.CharField(max_length=200)),
                ('texte', models.CharField(max_length=5000)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('piece_note', models.FileField(upload_to='')),
            ],
            options={
                'db_table': 'note',
            },
        ),
        migrations.CreateModel(
            name='PresenceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_conference', models.IntegerField()),
                ('id_personnel', models.IntegerField()),
                ('frequence', models.CharField(max_length=200)),
                ('date', models.DateField(null=True)),
                ('heure', models.TimeField()),
            ],
            options={
                'db_table': 'presence',
            },
        ),
    ]
