# Generated by Django 3.2 on 2021-04-11 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CongesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_personnel', models.IntegerField()),
                ('debut', models.DateField()),
                ('fin', models.DateField()),
            ],
            options={
                'db_table': 'conges',
            },
        ),
    ]
